version: '3'

networks:
  proxy-network:
    driver: bridge

services:
  proxy:
    build: .
    container_name: proxy
    restart: always
    networks:
      - proxy-network
    ports:
      - "8118:8118"
    # 确保容器能访问到192.168.1.202
    extra_hosts:
      - "host.docker.internal:host-gateway"

  n8n:
    image: n8nio/n8n
    container_name: n8n
    networks:
      - proxy-network
    ports:
      - "5678:5678"
    # 配置环境变量使用代理
    environment:
      - http_proxy=http://proxy:8118
      - https_proxy=http://proxy:8118
      - no_proxy=localhost,127.0.0.1,.local
      - N8N_SECURE_COOKIE=false
