version: '3.8'

services:
  # 替换为HTTP代理容器（tinyproxy）
  network-proxy:
    image: vimagick/tinyproxy:latest  # 支持HTTP代理的轻量级镜像
    container_name: network-proxy
    environment:
      - ALLOWED_NETWORKS=0.0.0.0/0  # 允许所有网络访问代理
      - UPSTREAM=http://172.23.128.1:10808  # 你的上游HTTP代理地址
    ports:
      - "8888:8888"  # tinyproxy默认端口为8888（HTTP代理）
    restart: unless-stopped
    networks:
      - proxy-network

  # n8n容器（适配HTTP代理）
  n8n:
    image: n8nio/n8n:1.42.1
    container_name: n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=your_secure_password  # 替换为你的密码
      - HTTP_PROXY=http://network-proxy:8888  # 指向HTTP代理容器
      - HTTPS_PROXY=http://network-proxy:8888  # HTTPS也通过HTTP代理转发
      - NO_PROXY=localhost,127.0.0.1,network-proxy
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - PUID=1000
      - PGID=1000
      - N8N_DISABLE_RUDDER=true  # 禁用Rudder避免额外代理问题
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - network-proxy
    restart: unless-stopped
    networks:
      - proxy-network
    entrypoint: ["n8n"]
    command: ["start"]

networks:
  proxy-network:
    driver: bridge

volumes:
  n8n_data:
    driver: local
    
